# Generated by Django 3.1.7 on 2021-03-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[
                 ('m', 'male'), ('f', 'female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('site', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(
                    help_text='Enter a technology name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=50)),
                ('vacancy_description', models.TextField(max_length=200)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[
                 ('r', 'RUB'), ('e', 'EUR'), ('u', 'USD')],
                    default='r', max_length=1)),
                ('publish_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='main.employer')),
                ('key_skill', models.ManyToManyField(
                    help_text='Select requiement(s) for vacancy',
                    to='main.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryMain',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('currency', models.CharField(choices=[
                 ('r', 'RUB'), ('e', 'EUR'), ('u', 'USD')],
                    default='r', max_length=1)),
                ('visibility_status', models.CharField(choices=[
                 ('v', 'Visible to anyone'), ('n', 'Not visible to anyone')],
                    default='v', max_length=1)),
                ('refresh_date', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='main.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=20)),
                ('year_begin', models.CharField(max_length=4)),
                ('month_begin', models.CharField(choices=[
                    ('00', ''),
                    ('01', 'January'),
                    ('02', 'Febraury'),
                    ('03', 'March'),
                    ('04', 'April'),
                    ('05', 'May'),
                    ('06', 'June'),
                    ('07', 'July'),
                    ('08', 'August'),
                    ('09', 'September'),
                    ('10', 'October'),
                    ('11', 'November'),
                    ('12', 'December')],
                    default='00', max_length=2)),
                ('year_end', models.CharField(max_length=4)),
                ('month_end', models.CharField(choices=[
                    ('00', ''),
                    ('01', 'January'),
                    ('02', 'Febraury'),
                    ('03', 'March'),
                    ('04', 'April'),
                    ('05', 'May'),
                    ('06', 'June'),
                    ('07', 'July'),
                    ('08', 'August'),
                    ('09', 'September'),
                    ('10', 'October'),
                    ('11', 'November'),
                    ('12', 'December')
                ],
                    default='00', max_length=2)),
                ('job_duty', models.TextField(max_length=500)),
                ('summary', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='main.summarymain')),
            ],
        ),
    ]
