# Generated by Django 3.1.7 on 2021-04-06 16:53

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True, validators=[
                                   main.validators.validate_age]),
        ),
    ]
