# Generated by Django 3.1.7 on 2021-04-08 05:12

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210406_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[main.validators.validate_age]),
        ),
    ]
