# Generated by Django 3.1.7 on 2021-04-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(blank=True, max_length=4, null=True)),
                ('server_response', models.TextField(max_length=200)),
            ],
        ),
    ]
