# Generated by Django 3.1.7 on 2021-05-03 19:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_smslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='skill',
        ),
        migrations.AddField(
            model_name='applicant',
            name='skill',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200, null=True), default=list, size=None),
        ),
    ]
